
# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a package using Gradle and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#Publishing-using-gradle


name: Build and deploy Java project to Azure Platform


env:
  AZURE_FUNCTIONAPP_NAME: Afunction # set this to your function app name on Azure
  PACKAGE_DIRECTORY: '.' # set this to the directory which contains pom.xml file
  JAVA_VERSION: '11' # set this to the java version to use
  ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}

on:
  workflow_dispatch:
  
  
    inputs:
      
       choice:
        type: choice
        description: Make a choice
        options:
        - INT-US
        - INT-EU
        - build.gradle
       #copy_tags:
        # description: 'True to Copy'
        # required: true
         #type: boolean
          
        
        
jobs:
  build:
    permissions:
     contents: read
     id-token: write
    runs-on: ubuntu-latest

    steps:
     
    
   #  - uses:  actions/checkout@v2

    #  - name: greet
    #    run: | 
    #      echo "environment is ${{ github.event.inputs.environment }}"
     #     echo "boolean is ${{ github.event.inputs.boolean }}"
      #    echo "choice is ${{ github.event.inputs.choice }}"
          
  
   
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v2
         
  
      - name: 'Install az func core tool'
        run: |
          wget -q https://packages.microsoft.com/config/ubuntu/20.04/packages-microsoft-prod.deb
          sudo dpkg -i packages-microsoft-prod.deb
          sudo apt-get update
         # sudo apt-get install azure-functions-core-tools-4
          
      - name: Setup Java Sdk ${{ env.JAVA_VERSION }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: 'temurin'  
          
          
      - name: 'Az CLI login'
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          
          
      - name: Build and deploy
        
        run: |
           
            if ${{ github.event.inputs.choice == 'INT-EU' }}
            then
                cp build.int.eu build.gradle    
            elif ${{ github.event.inputs.choice == 'INT-US' }}
            then
              cp build.int.us build.gradle
            fi
               gradle azureFunctionsDeploy

           


  
          
      

        
   


      

        
   


